### ISSUE TITLE
[BUG] "Mark all unread volumes/chapters before this as watched" not working

### ISSUE THREAD

**Issue by balajsra** [IgnisDa/ryot#1460]
When updating progress of a manga entry (which can be tracked as chapters or volumes), the "mark all unread volumes/chapters before this as watched" option doesn't appear to be working.

For example, I had previously read only chapter 1 of this manga, then read up to chapter 7. I attempted to update the progress as follows:

<img width="451" height="386" alt="Image" src="https://github.com/user-attachments/assets/50bd9d3e-9f7a-40a6-8a02-242fbcc04286" />

Then got these notifications:

<img width="465" height="174" alt="Image" src="https://github.com/user-attachments/assets/983f0446-9f2d-4f0c-b900-c72d1d56fcd6" />

Then when checking the history, it didn't actually add chapters 2-6, just chapter 7.

<img width="618" height="301" alt="Image" src="https://github.com/user-attachments/assets/f51499f5-0ec2-4094-a4fa-31d5be84652d" />

**Comment by IgnisDa** [comment]
I have fixed this and it will be available in the next release. Thanks for reporting!

**Comment by balajsra** [comment]
Just tried this on version 8.10.0 and it still appears to be broken, albeit in a different way. Now it prevents me from submitting the progress update because it thinks I specified both chapter and volume:

<img width="434" height="378" alt="Image" src="https://github.com/user-attachments/assets/68988091-b5df-4841-9724-43d1cf000e9f" />

<img width="437" height="55" alt="Image" src="https://github.com/user-attachments/assets/a2a4f73f-4a40-443e-8992-1d78a9d24999" />

**Comment by balajsra** [comment]
Interestingly, I noticed this issue only happens if you click on an item, go to the Actions tab and click Update Progress. If you click on the Play button in the grid view, it works fine.

**Comment by IgnisDa** [comment]
Can you please give me the steps to reproduce this? I tested it out on demo.ryot.io and it works fine from both the places you mentioned.

**Comment by balajsra** [comment]
I just tried it on demo.ryot.io and ran into the same issue.

Issue Occurs:

1. Click on Manga in left side tab menu
2. Click on one of the manga items in the grid (not the play button)
3. Actions -> Update Progress -> Mark CH-`number` as read
4. Enter a chapter number greater than the current progress and **enable** "Mark all unread volumes/chapters before this as watched". Then click submit and you should see error notification.

Issue Does Not Occur:

1. Click on Manga in left side tab menu
2. Click on the play button for one of the manga items in the grid
3. Enter a chapter number greater than the current progress and **enable** "Mark all unread volumes/chapters before this as watched". Then click submit and you will **not** see error notification.

**Comment by IgnisDa** [comment]
Can reproduce. Will fix.
