### ISSUE TITLE
bug - broken summary with sqlite

### ISSUE THREAD

**Issue by pbogre** [IgnisDa/ryot#211]
right now i have around 69 movies and some of them are rated, however the dashboard summary displays 0 for everything and reports that it was last updated in 1970.

when i try to force a regeneration of the summary through the settings and then go back to the dashboard, it will be loading for a while until i get the following error in the logs:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionAcquire', apps/backend/src/miscellaneous/resolver.rs:2778:54
```

and then it will still display no information.

perhaps related and this is some database error, but the import of my storygraph csv does not add any new books.

here is another error from the logs:

```
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', apps/backend/src/miscellaneous/resolver.rs:2133:22
```

**Comment by IgnisDa** [comment]
What version of Ryot are you using?

**Comment by IgnisDa** [comment]
This error generally occurs on SQLite. Can you try using postgres?

**Comment by IgnisDa** [comment]
> the import of my storygraph csv does not add any new books.

Can you email me the CSV? You can find my ID in my profile.

**Comment by pbogre** [comment]
> What version of Ryot are you using?

v1.16.3

> This error generally occurs on SQLite. Can you try using postgres?

Yes i am, is the summary only supported when using postgres? i will try switching to that now

> Can you email me the CSV? You can find my ID in my profile.

sure, although i think if the problem is using sqlite instead of postgres then that will also be fixed

**Comment by IgnisDa** [comment]
> summary only supported when using postgres

No it is supported on all, but I have no idea how to solve the problem you are getting. It has been reported earlier.

> although i think if the problem is using sqlite instead of postgres then that will also be fixed

I doubt that. I think it's a different error. Try again after switching to Postgres and if the error persists, then email me the export.

**Comment by IgnisDa** [comment]
Received your email. There was a small bug in the importer code. I published `v1.17.3` with the fix. It will take around 30 minutes to build the docker image. Please check with that.

**Comment by pbogre** [comment]
alright i made the switch to postgres and the summary seems to be working fine now. as you anticipated the storygraph bug is still there but im glad to hear you fixed it, ill check again later with the new image

**Comment by IgnisDa** [comment]
@pbogre were you able to test storygraph?

**Comment by pbogre** [comment]
> @pbogre were you able to test storygraph?

apologies for the late reply, yes i just updated the docker image and the version displays "v1.17.6", however the import still fails. now i have an option to view reports which is pretty great, so here's the error that is displayed for most books that errored: `"Could not convert ISBN: 9780881032475 to Openlibrary ID"`.

some entries have a number as the book's title which is odd, and that returns an error of course. here's an example of such entry:
```json
    {
        "lot": "BOOK",
        "step": "INPUT_TRANSFORMATION",
        "identifier": "28",
        "error": "CSV deserialize error: record 29 (line: 30, byte: 4056): field 9: cannot parse integer from empty string"
    }
```

**Comment by IgnisDa** [comment]
I suggest you manually update those. In case of storygraph, the identifier is the index of the row in the csv.

**Comment by pbogre** [comment]
i see, however with other entries the identifier was set as the book's title (example below)

```json
    {
        "lot": "BOOK",
        "step": "INPUT_TRANSFORMATION",
        "identifier": "The Stranger",
        "error": "Could not convert ISBN: 9780881032475 to Openlibrary ID"
    },
```

**Comment by IgnisDa** [comment]
Yes. Ryot tries it best, and fails at the last possible step. This is expected behaviour.
