### ISSUE TITLE
Importing from MediaTracker fails

### ISSUE THREAD

**Issue by pacjo** [IgnisDa/ryot#25]
Hi, I'm a fan of MediaTracker and I wanted to give your project a try. 
After some struggling with login #23 (even on 0.0.20 it didn't work without setting `insecure_cookie` to `true`, maybe add a note to readme?) I'm now stuck on importing.
I get a "Success" notification, but that's about as far as it goes. (one interesting thing is that "Success" is shown even if API key is incorrect, maybe different wording would help to avoid confusion? something like "Successfully accessed the URL / instance").

logs (portainer with timestamps):
```
2023-05-13T17:52:10.523496Z  INFO ryot: Using database backend: "SQLite"

2023-05-13T17:52:11.840217Z  INFO ryot: Listening on 0.0.0.0:8000

2023-05-13T17:52:41.860520Z  INFO ryot::background: Importing media

2023-05-13T17:52:41.869641Z  INFO ryot::misc::resolver: Started import job with id = 4

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', apps/backend/src/importer/media_tracker.rs:134:14

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by IgnisDa** [comment]
> I get a "Success" notification, but that's about as far as it goes. (one interesting thing is that "Success" is shown even if API key is incorrect, maybe different wording would help to avoid confusion?

Yes that makes sense. Clicking on import just deploys a background job.

> After some struggling with login https://github.com/IgnisDa/ryot/issues/23 (even on 0.0.20 it didn't work without setting insecure_cookie to true

What browser are you using?

As for the error, I think you might've discovered a bug. We are already storing the items that fail importing. I just need to make a page in the UI that displays all the jobs and their status.

**Comment by pacjo** [comment]
> What browser are you using?

Librewolf 112.0-1

> I'll fix the error itself tomorrow and ping you here so that you can test it.

happy to help

**Comment by IgnisDa** [comment]
@pacjo I released v0.0.21. Could you please test with it?

**Comment by pacjo** [comment]
It's getting a bit further, but still fails.

passed data:
url: `http://192.168.1.13:7481`
api key: `QWx************************c6Q` (30 characters)
```
2023-05-14T07:30:24.458489221Z 2023-05-14T07:30:24.458391Z  INFO ryot: Using database backend: "SQLite"

2023-05-14T07:30:25.782038072Z 2023-05-14T07:30:25.781836Z  INFO ryot: Listening on 0.0.0.0:8000

2023-05-14T07:31:18.226178772Z 2023-05-14T07:31:18.226061Z  INFO ryot::background: Importing media

2023-05-14T07:31:18.232267419Z 2023-05-14T07:31:18.231680Z  INFO ryot::misc::resolver: Started import job with id = 6

2023-05-14T07:31:18.294079075Z 2023-05-14T07:31:18.293922Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 723

2023-05-14T07:31:18.431658808Z 2023-05-14T07:31:18.431329Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 4579

2023-05-14T07:31:18.437885321Z 2023-05-14T07:31:18.437523Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 1029

2023-05-14T07:31:18.516499946Z 2023-05-14T07:31:18.516330Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 2003

2023-05-14T07:31:18.591674538Z 2023-05-14T07:31:18.591519Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 5721

2023-05-14T07:31:18.656051482Z 2023-05-14T07:31:18.655698Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 3320
```

**Comment by pacjo** [comment]
It's better, but there are still some issues.

Ryot didn't import everything and it's and MediaTracker's statistics differ:
![MT](https://github.com/IgnisDa/ryot/assets/56438628/fd375885-96d3-43c9-814d-84f922e8d125)
![RYOT](https://github.com/IgnisDa/ryot/assets/56438628/56964a1c-9ba3-4134-932e-34cffe4095d8)

logs:
```
2023-05-14T07:30:24.458489221Z 2023-05-14T07:30:24.458391Z  INFO ryot: Using database backend: "SQLite"

2023-05-14T07:30:25.782038072Z 2023-05-14T07:30:25.781836Z  INFO ryot: Listening on 0.0.0.0:8000

2023-05-14T07:31:18.226178772Z 2023-05-14T07:31:18.226061Z  INFO ryot::background: Importing media

2023-05-14T07:31:18.232267419Z 2023-05-14T07:31:18.231680Z  INFO ryot::misc::resolver: Started import job with id = 6

2023-05-14T07:31:18.294079075Z 2023-05-14T07:31:18.293922Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 723

2023-05-14T07:31:18.431658808Z 2023-05-14T07:31:18.431329Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 4579

2023-05-14T07:31:18.437885321Z 2023-05-14T07:31:18.437523Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 1029

2023-05-14T07:31:18.516499946Z 2023-05-14T07:31:18.516330Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 2003

2023-05-14T07:31:18.591674538Z 2023-05-14T07:31:18.591519Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 5721

2023-05-14T07:31:18.656051482Z 2023-05-14T07:31:18.655698Z ERROR ryot::importer::media_tracker: Encountered error: invalid type: null, expected an integer, a float, or a string containing a number at line 1 column 3320

2023-05-14T07:31:54.433453787Z 2023-05-14T07:31:54.433330Z ERROR ryot::importer: Error { message: "missing field `id` at line 1 column 100", extensions: None }

2023-05-14T07:32:26.696594821Z 2023-05-14T07:32:26.696476Z  INFO ryot::importer: Imported 53 media items from 'MT'

2023-05-14T07:35:00.427777549Z 2023-05-14T07:35:00.427667Z  INFO ryot::background: Running user and metadata association cleanup
```

**Comment by IgnisDa** [comment]
Would it be possible for you to share your MediaTracker API keys? The problem is that Ryot is expecting a different structure than what MediaTracker is sending. If you are able to share your API keys or a database dump, I'd be happy to look into it! You can email them to me at ignisda2001@gmail.com.

**Comment by pacjo** [comment]
> You can email them to me

Sent.

**Comment by IgnisDa** [comment]
Can you try with v0.0.22?

**Comment by pacjo** [comment]
It's better. Nearly everything got imported (it missed 1 movie and 9
episodes), ryot db attached.

logs:

2023-05-14T14:47:02.335041Z INFO ryot: Using database backend: "SQLite"

2023-05-14T14:47:04.398922Z INFO ryot: Listening on 0.0.0.0:8000

2023-05-14T14:47:20.387361Z INFO ryot::background: Running jobs after user
creation

2023-05-14T14:47:47.418818Z INFO ryot::background: Importing media

2023-05-14T14:47:47.423455Z INFO ryot::misc::resolver: Started import job
with id = 1

2023-05-14T14:48:26.226519Z ERROR ryot::importer: Error { message: "missing
field `id` at line 1 column 100", extensions: None }

2023-05-14T14:49:06.479955Z INFO ryot::importer: Imported 59 media items
from 'MT'

2023-05-14T14:50:00.309088Z INFO ryot::background: Running user and
metadata association cleanup




niedz., 14 maj 2023 o 16:37 Diptesh Choudhuri ***@***.***>
napisał(a):

**Comment by IgnisDa** [comment]
Please try with the latest version. I think it now works fine.

**Comment by pacjo** [comment]
Failed again, but there are good news.
Once again exactly 1 movie and 9 episodes didn't import. The movie is
"Lackadaisy" (YT short), but I don't know what's up with the TV shows. At
first I thought about duplicates, but then ryot should only import 716
things (as mediatracker presents it: "716 episodes (793 plays of 35
shows)").

**Comment by IgnisDa** [comment]
So the reason the movie is not being logged is because it is sourced from tmdb which Ryot does not support yet. Looking into the problem with episodes.

**Comment by pacjo** [comment]
Ok, this sounds good to me. Closing?
